//
// PriceEstimate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PriceEstimate: JSONEncodable {
    /** Unique identifier representing a specific product for a given latitude &amp; longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles */
    public var productId: String?
    /** [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code. */
    public var currencyCode: String?
    /** Display name of product. */
    public var displayName: String?
    /** Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or &quot;Metered&quot; for TAXI. */
    public var estimate: String?
    /** Lower bound of the estimated price. */
    public var lowEstimate: Double?
    /** Upper bound of the estimated price. */
    public var highEstimate: Double?
    /** Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier. */
    public var surgeMultiplier: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["product_id"] = self.productId
        nillableDictionary["currency_code"] = self.currencyCode
        nillableDictionary["display_name"] = self.displayName
        nillableDictionary["estimate"] = self.estimate
        nillableDictionary["low_estimate"] = self.lowEstimate
        nillableDictionary["high_estimate"] = self.highEstimate
        nillableDictionary["surge_multiplier"] = self.surgeMultiplier
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
