/**
 * Complex Api
 * Test schema to demonstrate ComplexAPI 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import SystemTestsRequests  from '../../src/api/SystemTestsRequests';

describe('SystemTestsApi', function(){
  let requests;
  beforeEach(function() {
    requests = new SystemTestsRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });

  });


    describe('testArrayOfStrings', function() {
      it('should send request testArrayOfStrings successfully', ()=> {
        //uncomment below and update the code to test testArrayOfStrings
        //return requests.testArrayOfStrings(key: any).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

    describe('testMultiArgs', function() {
      it('should send request testMultiArgs successfully', ()=> {
        //uncomment below and update the code to test testMultiArgs
        //return requests.testMultiArgs(key1: string, key2: number).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
