// flow-typed signature: 85874434ae38ee4f930f728ffcdd6874
// flow-typed version: <<STUB>>/dir-compare_v^1.3.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dir-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dir-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dir-compare/common' {
  declare module.exports: any;
}

declare module 'dir-compare/compareAsync' {
  declare module.exports: any;
}

declare module 'dir-compare/compareSync' {
  declare module.exports: any;
}

declare module 'dir-compare/defaultCompareFileCallback' {
  declare module.exports: any;
}

declare module 'dir-compare/defaultResultBuilderCallback' {
  declare module.exports: any;
}

declare module 'dir-compare/dircompare' {
  declare module.exports: any;
}

declare module 'dir-compare/filecompare' {
  declare module.exports: any;
}

declare module 'dir-compare/fileDescriptorQueue' {
  declare module.exports: any;
}

declare module 'dir-compare/print' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/extract' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/runTests' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/untar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dir-compare/common.js' {
  declare module.exports: $Exports<'dir-compare/common'>;
}
declare module 'dir-compare/compareAsync.js' {
  declare module.exports: $Exports<'dir-compare/compareAsync'>;
}
declare module 'dir-compare/compareSync.js' {
  declare module.exports: $Exports<'dir-compare/compareSync'>;
}
declare module 'dir-compare/defaultCompareFileCallback.js' {
  declare module.exports: $Exports<'dir-compare/defaultCompareFileCallback'>;
}
declare module 'dir-compare/defaultResultBuilderCallback.js' {
  declare module.exports: $Exports<'dir-compare/defaultResultBuilderCallback'>;
}
declare module 'dir-compare/dircompare.js' {
  declare module.exports: $Exports<'dir-compare/dircompare'>;
}
declare module 'dir-compare/filecompare.js' {
  declare module.exports: $Exports<'dir-compare/filecompare'>;
}
declare module 'dir-compare/fileDescriptorQueue.js' {
  declare module.exports: $Exports<'dir-compare/fileDescriptorQueue'>;
}
declare module 'dir-compare/index' {
  declare module.exports: $Exports<'dir-compare'>;
}
declare module 'dir-compare/index.js' {
  declare module.exports: $Exports<'dir-compare'>;
}
declare module 'dir-compare/print.js' {
  declare module.exports: $Exports<'dir-compare/print'>;
}
declare module 'dir-compare/tests/extract.js' {
  declare module.exports: $Exports<'dir-compare/tests/extract'>;
}
declare module 'dir-compare/tests/runTests.js' {
  declare module.exports: $Exports<'dir-compare/tests/runTests'>;
}
declare module 'dir-compare/tests/untar.js' {
  declare module.exports: $Exports<'dir-compare/tests/untar'>;
}
