// flow-typed signature: 5de636f81d1aa6b6bd636552b5662519
// flow-typed version: <<STUB>>/dirty-chai_v^1.2.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dirty-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dirty-chai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dirty-chai/Gruntfile' {
  declare module.exports: any;
}

declare module 'dirty-chai/lib/dirty-chai' {
  declare module.exports: any;
}

declare module 'dirty-chai/test/chai-as-promised-integration' {
  declare module.exports: any;
}

declare module 'dirty-chai/test/common' {
  declare module.exports: any;
}

declare module 'dirty-chai/test/dirty-chai.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dirty-chai/Gruntfile.js' {
  declare module.exports: $Exports<'dirty-chai/Gruntfile'>;
}
declare module 'dirty-chai/lib/dirty-chai.js' {
  declare module.exports: $Exports<'dirty-chai/lib/dirty-chai'>;
}
declare module 'dirty-chai/test/chai-as-promised-integration.js' {
  declare module.exports: $Exports<'dirty-chai/test/chai-as-promised-integration'>;
}
declare module 'dirty-chai/test/common.js' {
  declare module.exports: $Exports<'dirty-chai/test/common'>;
}
declare module 'dirty-chai/test/dirty-chai.spec.js' {
  declare module.exports: $Exports<'dirty-chai/test/dirty-chai.spec'>;
}
