// flow-typed signature: 336c43715c6444f3aa2a2cc6b85ba187
// flow-typed version: <<STUB>>/istanbul-combine_v^0.3.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'istanbul-combine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'istanbul-combine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'istanbul-combine/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'istanbul-combine/cli.js' {
  declare module.exports: $Exports<'istanbul-combine/cli'>;
}
declare module 'istanbul-combine/index' {
  declare module.exports: $Exports<'istanbul-combine'>;
}
declare module 'istanbul-combine/index.js' {
  declare module.exports: $Exports<'istanbul-combine'>;
}
