/**
 * Uber API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.api;

import io.swagger.client.ApiInvoker;
import io.swagger.client.ApiException;
import io.swagger.client.Pair;

import io.swagger.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import io.swagger.client.model.Error;
import io.swagger.client.model.PriceEstimate;
import io.swagger.client.model.Product;
import java.util.UUID;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class EstimatesApi {
  String basePath = "https://api.uber.com/v1";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Price Estimates
  * The Price Estimates endpoint returns an estimated price range for each product offered at a given location. The price estimate is provided as a formatted string with the full price range and the localized currency symbol.&lt;br&gt;&lt;br&gt;The response also includes low and high estimates, and the [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code for situations requiring currency conversion. When surge is active for a particular product, its surge_multiplier will be greater than 1, but the price estimate already factors in this multiplier.
   * @param startLatitude Latitude component of start location.
   * @param startLongitude Longitude component of start location.
   * @param endLatitude Latitude component of end location.
   * @param endLongitude Longitude component of end location.
   * @return List<PriceEstimate>
  */
  public List<PriceEstimate> estimatesPriceGet (Double startLatitude, Double startLongitude, Double endLatitude, Double endLongitude) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
     Object postBody = null;
      // verify the required parameter 'startLatitude' is set
      if (startLatitude == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'startLatitude' when calling estimatesPriceGet",
      new ApiException(400, "Missing the required parameter 'startLatitude' when calling estimatesPriceGet"));
      }
      // verify the required parameter 'startLongitude' is set
      if (startLongitude == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'startLongitude' when calling estimatesPriceGet",
      new ApiException(400, "Missing the required parameter 'startLongitude' when calling estimatesPriceGet"));
      }
      // verify the required parameter 'endLatitude' is set
      if (endLatitude == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'endLatitude' when calling estimatesPriceGet",
      new ApiException(400, "Missing the required parameter 'endLatitude' when calling estimatesPriceGet"));
      }
      // verify the required parameter 'endLongitude' is set
      if (endLongitude == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'endLongitude' when calling estimatesPriceGet",
      new ApiException(400, "Missing the required parameter 'endLongitude' when calling estimatesPriceGet"));
      }

  // create path and map variables
  String path = "/estimates/price".replaceAll("\\{format\\}","json");

  // query params
  List<Pair> queryParams = new ArrayList<Pair>();
      // header params
      Map<String, String> headerParams = new HashMap<String, String>();
      // form params
      Map<String, String> formParams = new HashMap<String, String>();

          queryParams.addAll(ApiInvoker.parameterToPairs("", "start_latitude", startLatitude));
          queryParams.addAll(ApiInvoker.parameterToPairs("", "start_longitude", startLongitude));
          queryParams.addAll(ApiInvoker.parameterToPairs("", "end_latitude", endLatitude));
          queryParams.addAll(ApiInvoker.parameterToPairs("", "end_longitude", endLongitude));


      String[] contentTypes = {
  
      };
      String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

      if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
      } else {
      // normal form params
        }

      String[] authNames = new String[] {  };

      try {
        String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
        if(localVarResponse != null){
           return (List<PriceEstimate>) ApiInvoker.deserialize(localVarResponse, "array", PriceEstimate.class);
        } else {
           return null;
        }
      } catch (ApiException ex) {
         throw ex;
      } catch (InterruptedException ex) {
         throw ex;
      } catch (ExecutionException ex) {
         if(ex.getCause() instanceof VolleyError) {
	    VolleyError volleyError = (VolleyError)ex.getCause();
	    if (volleyError.networkResponse != null) {
	       throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
	    }
         }
         throw ex;
      } catch (TimeoutException ex) {
         throw ex;
      }
  }

      /**
   * Price Estimates
   * The Price Estimates endpoint returns an estimated price range for each product offered at a given location. The price estimate is provided as a formatted string with the full price range and the localized currency symbol.&lt;br&gt;&lt;br&gt;The response also includes low and high estimates, and the [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code for situations requiring currency conversion. When surge is active for a particular product, its surge_multiplier will be greater than 1, but the price estimate already factors in this multiplier.
   * @param startLatitude Latitude component of start location.   * @param startLongitude Longitude component of start location.   * @param endLatitude Latitude component of end location.   * @param endLongitude Longitude component of end location.
  */
  public void estimatesPriceGet (Double startLatitude, Double startLongitude, Double endLatitude, Double endLongitude, final Response.Listener<List<PriceEstimate>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'startLatitude' is set
    if (startLatitude == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'startLatitude' when calling estimatesPriceGet",
         new ApiException(400, "Missing the required parameter 'startLatitude' when calling estimatesPriceGet"));
    }
    // verify the required parameter 'startLongitude' is set
    if (startLongitude == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'startLongitude' when calling estimatesPriceGet",
         new ApiException(400, "Missing the required parameter 'startLongitude' when calling estimatesPriceGet"));
    }
    // verify the required parameter 'endLatitude' is set
    if (endLatitude == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'endLatitude' when calling estimatesPriceGet",
         new ApiException(400, "Missing the required parameter 'endLatitude' when calling estimatesPriceGet"));
    }
    // verify the required parameter 'endLongitude' is set
    if (endLongitude == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'endLongitude' when calling estimatesPriceGet",
         new ApiException(400, "Missing the required parameter 'endLongitude' when calling estimatesPriceGet"));
    }

    // create path and map variables
    String path = "/estimates/price".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();

    queryParams.addAll(ApiInvoker.parameterToPairs("", "start_latitude", startLatitude));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start_longitude", startLongitude));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end_latitude", endLatitude));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "end_longitude", endLongitude));


    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

      String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<PriceEstimate>) ApiInvoker.deserialize(localVarResponse,  "array", PriceEstimate.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Time Estimates
  * The Time Estimates endpoint returns ETAs for all products offered at a given location, with the responses expressed as integers in seconds. We recommend that this endpoint be called every minute to provide the most accurate, up-to-date ETAs.
   * @param startLatitude Latitude component of start location.
   * @param startLongitude Longitude component of start location.
   * @param customerUuid Unique customer identifier to be used for experience customization.
   * @param productId Unique identifier representing a specific product for a given latitude &amp; longitude.
   * @return List<Product>
  */
  public List<Product> estimatesTimeGet (Double startLatitude, Double startLongitude, UUID customerUuid, String productId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
     Object postBody = null;
      // verify the required parameter 'startLatitude' is set
      if (startLatitude == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'startLatitude' when calling estimatesTimeGet",
      new ApiException(400, "Missing the required parameter 'startLatitude' when calling estimatesTimeGet"));
      }
      // verify the required parameter 'startLongitude' is set
      if (startLongitude == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'startLongitude' when calling estimatesTimeGet",
      new ApiException(400, "Missing the required parameter 'startLongitude' when calling estimatesTimeGet"));
      }

  // create path and map variables
  String path = "/estimates/time".replaceAll("\\{format\\}","json");

  // query params
  List<Pair> queryParams = new ArrayList<Pair>();
      // header params
      Map<String, String> headerParams = new HashMap<String, String>();
      // form params
      Map<String, String> formParams = new HashMap<String, String>();

          queryParams.addAll(ApiInvoker.parameterToPairs("", "start_latitude", startLatitude));
          queryParams.addAll(ApiInvoker.parameterToPairs("", "start_longitude", startLongitude));
          queryParams.addAll(ApiInvoker.parameterToPairs("", "customer_uuid", customerUuid));
          queryParams.addAll(ApiInvoker.parameterToPairs("", "product_id", productId));


      String[] contentTypes = {
  
      };
      String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

      if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
      } else {
      // normal form params
        }

      String[] authNames = new String[] {  };

      try {
        String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
        if(localVarResponse != null){
           return (List<Product>) ApiInvoker.deserialize(localVarResponse, "array", Product.class);
        } else {
           return null;
        }
      } catch (ApiException ex) {
         throw ex;
      } catch (InterruptedException ex) {
         throw ex;
      } catch (ExecutionException ex) {
         if(ex.getCause() instanceof VolleyError) {
	    VolleyError volleyError = (VolleyError)ex.getCause();
	    if (volleyError.networkResponse != null) {
	       throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
	    }
         }
         throw ex;
      } catch (TimeoutException ex) {
         throw ex;
      }
  }

      /**
   * Time Estimates
   * The Time Estimates endpoint returns ETAs for all products offered at a given location, with the responses expressed as integers in seconds. We recommend that this endpoint be called every minute to provide the most accurate, up-to-date ETAs.
   * @param startLatitude Latitude component of start location.   * @param startLongitude Longitude component of start location.   * @param customerUuid Unique customer identifier to be used for experience customization.   * @param productId Unique identifier representing a specific product for a given latitude &amp; longitude.
  */
  public void estimatesTimeGet (Double startLatitude, Double startLongitude, UUID customerUuid, String productId, final Response.Listener<List<Product>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'startLatitude' is set
    if (startLatitude == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'startLatitude' when calling estimatesTimeGet",
         new ApiException(400, "Missing the required parameter 'startLatitude' when calling estimatesTimeGet"));
    }
    // verify the required parameter 'startLongitude' is set
    if (startLongitude == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'startLongitude' when calling estimatesTimeGet",
         new ApiException(400, "Missing the required parameter 'startLongitude' when calling estimatesTimeGet"));
    }

    // create path and map variables
    String path = "/estimates/time".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();

    queryParams.addAll(ApiInvoker.parameterToPairs("", "start_latitude", startLatitude));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "start_longitude", startLongitude));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "customer_uuid", customerUuid));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "product_id", productId));


    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

      String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<Product>) ApiInvoker.deserialize(localVarResponse,  "array", Product.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
