/*
 * Complex Api
 * Test schema to demonstrate ComplexAPI
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import {expect} from 'chai';

import SystemTestEventEvents from '../../src/api/SystemTestEventEvents';

describe('SystemTestEventApi', function () {
  let events;
  beforeEach(function () {
    events = new SystemTestEventEvents({
      registerEventListener() {
      },
      emitEvent() {
      },
    });
  });

  describe('testEvent', function () {
    it('should emit event testEvent successfully', done => {
      // uncomment below and update the code to test testEvent
      //events.addTestEventEventListener(() => done());
      //events.emitTestEvent(buttonId: string);
      done();
    });
  });
});
