/*
 * Complex Api
 * Test schema to demonstrate ComplexAPI
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import SystemTestEventEvents from '../../src/api/SystemTestEventEvents';

describe('SystemTestEventApi', function () {
  let events;
  beforeEach(function () {
    let eventListener;
    events = new SystemTestEventEvents({
      registerEventListener(name, listener) {
        eventListener = listener;
      },
      emitEvent(name, data) {
        eventListener && eventListener(data);
      },
    });
  });

  describe('testEvent', () => {
    it('emits "testEvent" event', () => {
      const listener = jest.fn();
      events.addTestEventEventListener(listener);
      events.emitTestEvent('id');
      expect(listener).toHaveBeenCalledWith({data: 'id'});
    });
  });
});
