/*
 * Complex Api
 * Test schema to demonstrate ComplexAPI
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import {expect} from 'chai';

import TestEventObjectParamEvents from '../../src/api/TestEventObjectParamEvents';

describe('TestEventObjectParamApi', function () {
  let events;
  beforeEach(function () {
    events = new TestEventObjectParamEvents({
      registerEventListener() {
      },
      emitEvent() {
      },
    });
  });

  describe('testEventObjectParam', function () {
    it('should emit event testEventObjectParam successfully', done => {
      // uncomment below and update the code to test testEventObjectParam
      //events.addTestEventObjectParamEventListener(() => done());
      //events.emitTestEventObjectParam(opts: any);
      done();
    });
  });
});
