/*
 * Complex Api
 * Test schema to demonstrate ComplexAPI
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import TestEventObjectParamEvents from '../../src/api/TestEventObjectParamEvents';

describe('TestEventObjectParamApi', function () {
  let events;
  beforeEach(function () {
    let eventListener;
    events = new TestEventObjectParamEvents({
      registerEventListener(name, listener) {
        eventListener = listener;
      },
      emitEvent(name, data) {
        eventListener && eventListener(data);
      },
    });
  });

  describe('testEventObjectParam', () => {
    it('emits "testEventObjectParam" event', () => {
      const listener = jest.fn();
      events.addTestEventObjectParamEventListener(listener);
      events.emitTestEventObjectParam('id');
      expect(listener).toHaveBeenCalledWith({data: 'id'});
    });
  });
});
