declare module 'node-ipc'
declare module 'code-push'
declare module 'node-simctl'
declare module 'xcode-ern'
declare module 'gradle-to-js/lib/parser'
declare module 'decompress-zip'
declare module 'ern-bugsnag-sourcemaps'
