/**
 * Complex Api
 * Test schema to demonstrate ComplexAPI 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import SysteTestEventEvents  from '../../src/api/SysteTestEventEvents';

describe('SysteTestEventApi', function(){
  let events;
  beforeEach(function() {
    events = new SysteTestEventEvents({
        registerEventListener(){
        },
        emitEvent(){
        }
    });

  });


    describe('testEvent', function() {
        it('should emit event testEvent successfully', (done)=> {
        //uncomment below and update the code to test testEvent
        //register listener.
        //events.addTestEventEventListener(()=>done());
        //emit event.
        //events.emitTestEvent(buttonId: string);
        //});
        done();
        });
    });

});
