apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace "com.walmartlabs.ern.container"
    compileSdkVersion 35
    buildToolsVersion "35.0.0"
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 35
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.0'
    }
    sourceSets.main {
        res.srcDirs = [ 'src/main/res/bundle','src/main/res/devassist','src/main/res/miniapp' ]
    }
    lintOptions {
        abortOnError false
    }
    publishing {
        multipleVariants {
            allVariants()
        }
    }
}

dependencies {
    api 'com.walmartlabs.ern:react-android:0.63.4'
}

gradle.projectsEvaluated {
    android.buildTypes.each {
        it.resValue 'string', "CODE_PUSH_APK_BUILD_TIME", Long.toString(System.currentTimeMillis())
    }
}
