/*
 * WalmartItem
 * Walmart Item Module
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import WalmartItemRequests from '../../src/api/WalmartItemRequests';
import WalmartItemEvents from '../../src/api/WalmartItemEvents';

describe('WalmartItemApi', function () {
  let requests;
  let events;
  beforeEach(function () {
    let requestHandler;
    requests = new WalmartItemRequests({
      registerRequestHandler(name, handler) {
        requestHandler = handler;
      },
      sendRequest(name, data) {
        requestHandler && requestHandler(data);
        return Promise.resolve(data);
      },
    });
    let eventListener;
    events = new WalmartItemEvents({
      registerEventListener(name, listener) {
        eventListener = listener;
      },
      emitEvent(name, data) {
        eventListener && eventListener(data);
      },
    });
  });

  describe('addItem', () => {
    it('sends "addItem" request', () => {
      return requests.addItem('id').then(response => {
        expect(response).toEqual({data: 'id', timeout: undefined});
      });
    });
  });

  describe('findItems', () => {
    it('sends "findItems" request', () => {
      return requests.findItems('id').then(response => {
        expect(response).toEqual({data: 'id', timeout: undefined});
      });
    });
  });

  describe('itemAdded', () => {
    it('emits "itemAdded" event', () => {
      const listener = jest.fn();
      events.addItemAddedEventListener(listener);
      events.emitItemAdded('id');
      expect(listener).toHaveBeenCalledWith({data: 'id'});
    });
  });
});
